### ISSUE TITLE
Move from rackspace

### ISSUE THREAD

**Issue by mattip** [yt-project/yt-wheels#7]
Given the uncertainty around travis-ci, you may want to look at this [github action from scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/master/.github/workflows/wheels.yml) and adopt it to your workflow. If you want tokens to upload to the scientific stack's anaconda areas on https://anaconda.org/scipy-wheels-nightly/ for developer wheels and/or https://anaconda.org/multibuild-wheels-staging for staging before deployment let me know.

**Comment by munkm** [comment]
Thanks for the tip about the github action @mattip! 

We would love tokens to upload to multibuild-wheels-staging for our pre-pypi wheels. What information do you need from us for that? And do we need to make any other changes in this repo migrate from rackspace?

**Comment by mattip** [comment]
You need to use the anaconda client like in the action I pointed to. The [pywavelets](https://github.com/MacPython/pywavelets-wheels) people may be able to help, they also moved lately but remained on travis/appveyor. 

Let me know your user name on anaconda.org and I can add you to the group. Then you need to create a token at https://anaconda.org/multibuild-wheels-staging/settings/access. It should have permissions to 
- "Allow write access to the API site"
- "Allow uploads to PyPI repositories"

as per [this comment](https://github.com/MacPython/pywavelets-wheels/pull/13#issuecomment-702839599).

**Comment by munkm** [comment]
Ok, thanks! My username on anaconda.org is `munkm`.

**Comment by mattip** [comment]
done.

**Comment by munkm** [comment]
Thank you so much for your help @mattip !! It looks like everything is showing up on anaconda.org now. If we do end up starting to do nightlies I'll be sure to contact you again.
